### ISSUE TITLE
Username with number

### ISSUE THREAD

**Issue by dantremblay** [kassisol/tsa#2]
Hi,

When using a Username with a number (ex: hrcsi3), we get :

> FATA[0018] Cannot use FQDN for client CN

Please see this PR: https://github.com/kassisol/tsa/pull/1

Thanks

**Comment by ghost** [comment]
Hi,

I have replied to PR. I will try to update the problematic package this weekend.

Thanks

**Comment by ghost** [comment]
package updated and fixed the err condition.
